[tool.ruff]
line-length = 88
target-version = "py312"
fix = true

ignore = ["E501", "F401", "DJ008", "E722", "F811"]

select = [
    "E",
    "F",
    "I",
    "UP",
    "DJ",
]

exclude = [
    "migrations",
    "venv",
    "__pycache__",
]

[tool.ruff.isort]
combine-as-imports = true
known-first-party = ["testtask"]

[tool.ruff.per-file-ignores]
"settings.py" = ["F403"]